# Generated by Django 2.2.2 on 2019-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
