# Generated by Django 2.2.2 on 2019-09-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20190827_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
