# Generated by Django 2.1 on 2019-03-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190331_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_num',
            field=models.CharField(max_length=50),
        ),
    ]
