# Generated by Django 2.1 on 2019-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_remove_food_store'),
        ('Store', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='foods',
            field=models.ManyToManyField(to='Food.Food'),
        ),
    ]
