# Generated by Django 2.1 on 2019-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_store_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='store',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
