# Generated by Django 2.1 on 2019-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20190403_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
