# Generated by Django 2.1 on 2019-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20190403_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
