# Generated by Django 2.2.2 on 2019-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_auto_20190804_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='education_degree',
            field=models.CharField(choices=[('0', 'UnderGraduated'), ('1', 'Graduated'), ('2', 'Master'), ('3', 'PH.D')], max_length=50, null=True),
        ),
    ]
