# Generated by Django 2.2.2 on 2019-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_manager_education_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education_degree',
            field=models.CharField(choices=[('0', 'UnderGraduated'), ('1', 'Graduated'), ('2', 'Master'), ('3', 'PH.D')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Employee Images/'),
        ),
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Manager Images/'),
        ),
    ]
