# Generated by Django 2.2.2 on 2019-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_auto_20190831_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('0', 'UnderGraduated'), ('1', 'Graduated'), ('2', 'Master'), ('3', 'PH.D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('0', 'UnderGraduated'), ('1', 'Graduated'), ('2', 'Master'), ('3', 'PH.D')], max_length=50, null=True),
        ),
    ]
