# Generated by Django 2.2.2 on 2019-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20190831_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('1', 'Cashier'), ('2', 'Waiter'), ('3', 'Waitress'), ('4', 'Head Chef'), ('5', 'Chef'), ('6', 'Accountant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
