# Generated by Django 2.2.2 on 2019-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_auto_20190831_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
