# Generated by Django 2.2.2 on 2019-08-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_store_monthly_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='monthly_income',
        ),
    ]
