# Generated by Django 2.2.2 on 2019-08-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_remove_store_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('UnderGraduated', 'UnderGraduated'), ('Graduated', 'Graduated'), ('Master', 'Master'), ('PH', 'PH.D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Waitress', 'Waitress'), ('Head Chef', 'Head Chef'), ('Chef', 'Chef'), ('Accountant', 'Accountant')], max_length=50, null=True),
        ),
    ]
