# Generated by Django 2.2.2 on 2019-09-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20190901_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('UnderGraduated', 'UnderGraduated'), ('Graduated', 'Graduated'), ('Master', 'Master'), ('PH.D', 'PH.D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='Store.Manager'),
        ),
    ]
