# Generated by Django 2.2.2 on 2019-09-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0019_food_run_out'),
        ('Comment', '0002_auto_20190903_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Food.Food'),
        ),
    ]
