# Generated by Django 2.2.2 on 2019-09-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_auto_20190903_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Food.Food'),
        ),
    ]
