# Generated by Django 2.1 on 2019-03-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_remove_food_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
