# Generated by Django 2.1 on 2019-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20190331_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
