# Generated by Django 2.1 on 2019-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0005_auto_20190403_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
