# Generated by Django 2.1 on 2019-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_food_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
