# Generated by Django 2.2.2 on 2019-08-18 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food', '0016_auto_20190628_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='foods_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
