# Generated by Django 2.2.2 on 2019-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0017_food_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
