# Generated by Django 2.2.2 on 2019-09-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0019_food_run_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='users_like',
        ),
    ]
